# Generated by Django 4.2.14 on 2024-10-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('porter_term', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadxml',
            name='file',
            field=models.FileField(upload_to='./search_engine/data'),
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='search_engine.words')),
            ],
        ),
    ]
